maestrano/mnoe-admin-panel

- src/app/index.less
- src/fonts/font-faces.less
> Fix custom fonts

- src/app/components/mnoe-reviews-list/mnoe-reviews-list.html
- src/app/views/user/user.html
@alexnoox please review
Quick fix, just realised that I forgot the review page (which was not showing on mno-enterprise-demo).
also for got an rd-loading.
I checked carefully and there are no rdash left!
> Add mno-widget to the review page

- src/app/components/mnoe-api/admin/current-user.svc.coffee
- src/app/components/mnoe-api/admin/users.svc.coffee
- src/app/components/mnoe-staffs-list/mnoe-staffs-list.coffee
- src/app/components/mnoe-staffs-list/mnoe-staffs-list.html
- src/app/services/mnoe-observables/mnoe-observables.coffee
- src/app/views/customers/customers.controller.coffee
- src/app/views/dashboard.controller.coffee
- src/app/views/dashboard.layout.html
- src/app/views/staff/create-staff-modal/create-staff.controller.coffee
- src/app/views/staff/staff.controller.coffee
- src/locales/en-AU.json
Rewrote the changes applied on the following PR:
https://github.com/maestrano/mno-enterprise/pull/182
@alexnoox can you review this please? :)
> [MNOE-155] - Staff invite Workflow

- src/app/components/mnoe-organizations-local-list/mnoe-organizations-local-list.html
- src/app/components/mnoe-users-local-list/mnoe-users-local-list.html
@ouranos Please review and merge
> Fix locales

- src/app/components/mnoe-config/mnoe-admin-config.svc.coffee
- src/app/views/organization/organization.html
Do not display CC info if billing or payment is disabled in the
frontend.
> Feature Flag - Don't display CC info

- src/app/components/mnoe-users-local-list/mnoe-users-local-list.coffee
> [MNOE-307] - Impersonate with the right organization

- src/app/index.less
- src/app/index.run.coffee
> Display error message when connecting wrong Xero

- gulp_tasks/styles.js
> Default variables: Force LESS files compilation order

- src/app/index.less
- src/app/views/settings/settings.controller.coffee
- src/app/views/settings/settings.html
- src/app/views/settings/settings.less
@ouranos Please review and merge
Theme validated by @BrunoChauvet
> [MNOE-448] Settings: Polish style & save button loader

- src/app/components/mnoe-config/mnoe-admin-config.svc.coffee
- src/app/views/customers/customers.html
The invite email is a link to the registration page
> [MNOE-449] Disable invite when registration is disabled

- src/app/index.less
- src/index.html
@alexnoox I think this should take care of the FOUC issue 👍
> [MNOE-555] Fix FOUC using translate-cloak

- src/app/components/mnoe-api/admin/tasks.svc.coffee
+ move the file with the other services
> Add a hack to display to show user first name, last name and orga

- bower.json
- src/app/impac.config.coffee
- src/app/views/impac/impac.less
> Use demo_mode on dashboard templates designer

- src/app/components/mnoe-app-metrics-list/mno-app-metrics-list.html
> [MNOE-479] - Fix UI for apps listing when Finance is disabled

- src/app/components/mnoe-tasks/mnoe-tasks.coffee
@alexnoox please review & merge
> Fix due tasks filter to exclude done tasks

- src/app/components/mnoe-api/admin/sub-tenants.svc.coffee
- src/app/components/mnoe-config/mnoe-admin-config.svc.coffee
- src/app/components/mnoe-organizations-list/mnoe-organizations-list.coffee
- src/app/components/mnoe-staffs-list/mnoe-staffs-list.coffee
- src/app/components/mnoe-sub-tenants-list/mnoe-sub-tenants-list.coffee
- src/app/components/mnoe-sub-tenants-list/mnoe-sub-tenants-list.html
- src/app/index.config.coffee
- src/app/index.constants.coffee
- src/app/index.route.coffee
- src/app/views/staff/staff.controller.coffee
- src/app/views/staff/update-staff-clients-modal/update-staff-clients.controller.coffee
- src/app/views/staffs/staffs.controller.coffee
- src/app/views/sub-tenant/sub-tenant.html
- src/app/views/sub-tenant/update-account-managers-modal/update-account-managers.controller.coffee
- src/app/views/sub-tenant/update-account-managers-modal/update-account-managers.html
- src/app/views/sub-tenant/update-clients-modal/update-clients.controller.coffee
- src/app/views/sub-tenant/update-clients-modal/update-clients.html
- src/app/views/sub-tenants/create-sub-tenant-modal/create-sub-tenant.controller.coffee
- src/app/views/sub-tenants/create-sub-tenant-modal/create-sub-tenant.less
- src/app/views/sub-tenants/sub-tenants.controller.coffee
- src/app/views/sub-tenants/sub-tenants.html
- src/locales/en-AU.json
Linked to PR: #36
- Remove double empty lines
- Fix indentation
- Remove useless state
- Remove useless less file
> Apply code review comments from #36

- src/app/views/product-markups/create-markup-modal/create-markup.html
> [MNOE-476] - Fix closing markup

- src/app/components/mno-pagination/mno-pagination.coffee
- MnoHub Api v2 supports up to 50 elements for pagination
> Remove 100 from pagination

- src/app/views/settings/plugins/plugins.controller.coffee
> [MNOE-599] Add payment gateway eWay

- src/app/components/mnoe-config/mnoe-admin-config.svc.coffee
- src/app/components/mnoe-product-markups-list/mnoe-product-markups-list.coffee
- src/app/components/mnoe-staffs-list/mnoe-staffs-list.coffee
- src/app/components/mnoe-staffs-local-list/mnoe-staffs-local-list.coffee
- src/app/index.route.coffee
- src/app/views/dashboard.layout.html
- src/app/views/staff/staff.controller.coffee
- src/app/views/staffs/create-staff-modal/create-staff.controller.coffee
- src/app/views/sub-tenant/update-account-managers-modal/update-account-managers.controller.coffee
* Hide subtenant roles when subtenants are disabled
* Hide Audit Log for non admin
> [MNOE-483][MNOE-604] SubTenant fixes

- src/app/components/mnoe-api/admin/apps.svc.coffee
- src/app/components/mnoe-api/marketplace.svc.coffee
- src/app/index.constants.coffee
- src/app/views/settings/apps/apps.controller.coffee
- src/app/views/settings/general/general.controller.coffee
- src/app/views/settings/plugins/plugins.controller.coffee
* Refresh marketplace when enabling/disabling apps
* The JSON schema is now returned via the Tenant endpoint
* Filter the App list available in the configuration to match the catalogu
> [MNOE-598] Config refactor and fix App selection

- src/app/components/mnoe-products-list/mnoe-products-list.controller.coffee
Product_id added as a filterable attribute on mnohub side
> Fix product_id filtering

- src/app/components/mnoe-config/mnoe-admin-config.svc.coffee
- src/app/views/organization/organization.controller.coffee
- src/app/views/organization/organization.html
- src/locales/en-AU.json
> Select currency of user in Organisation Page in Admin Panel

- src/app/views/impac/impac.less
- [EMERALD-37] Hide data sources from the template edition page
> Fixes - Dashboard templates designer

- src/app/components/mnoe-sub-tenants-list/mnoe-sub-tenants-list.coffee
@alexnoox Please review. I will leave a comment about this in the JIRA as I cannot link the ticket. :)
> [BUG] Fix locale typo

- src/app/components/mnoe-api/admin/provisioning.svc.coffee
Fix order edition. Create and update responses are a bit different.
> Fix modification of orders

- bower.json
- src/app/views/provisioning/confirm.html
- src/app/views/provisioning/details.controller.coffee
Summary of changes:
- Fix edit order link on provisioning workflow
- Fix parsing of nested objects in json schemas
- Add datepicker for angular-schema-form
> [MNOE-594] Fix product provisioning - add date-time fields

- bower.json
- src/app/index.config.coffee
- src/app/index.module.coffee
- src/app/views/orders/order.controller.coffee
- src/app/views/orders/order.html
This PR enhance the JSON data tree rendering:
It is possible to expand/collapse the JSON tree and there is a preview on hover.
This code is using this angular directive: https://github.com/mohsen1/json-formatter
> [MNOE-603] Use a directive to display JSON in HTML

- src/app/views/provisioning/confirm.html
- src/app/views/provisioning/order.controller.coffee
- src/app/views/provisioning/order.html
- src/app/views/provisioning/summary.html
- src/locales/en-AU.json
> [MNOE-685] Display pricing type on order pages

- src/app/components/mnoe-users-local-list/mnoe-users-local-list.html
- src/app/views/user/user.html
- src/locales/en-AU.json
Backporting #125 to `1.0` branch
> [MNOE-658][MNOE-699] Disallow staff impersonation

- src/app/components/mnoe-staffs-list/mnoe-staffs-list.coffee
- src/app/components/mnoe-staffs-list/mnoe-staffs-list.html
- src/app/views/staff/staff.html
> [MNOE-720] Fix staff pagination

- src/app/components/mnoe-modals/comment-edit-modal.coffee
- src/app/components/mnoe-reviews-list/mnoe-reviews-list.coffee
> [MNOE-701] Fix admin can not edit reviews or cancel editions

- src/app/components/mnoe-reviews-list/mnoe-reviews-list.coffee
> [MNOE-701] Fix edition of comments on comments

- src/app/index.config.coffee
Same as maestrano/mno-enterprise-angular#380
> [MNOE-788] Add password expiration interceptor

- conf/browsersync-dist.conf.js
- gulp_tasks/browsersync.js
> Fix gulp serve dist

- src/index.html
> [MNOE-793] Rename Admin Panel to Control Panel

- src/app/views/dashboard.layout.html
- Align ACL with routes (subtenant admin should not access settings)
- Fix problem  with condition
> Fix settings menu for feature flag

- src/app/views/dashboard.layout.html
> [MNOE-809] Fix Product Markup feature flags

- src/app/components/mnoe-app-metrics-list/mno-app-metrics-list.coffee
Actual fix depends on following PRs, but no hard dependency (won't break anything if deployed first):
https://github.com/maestrano/maestrano-hub/pull/826
https://github.com/maestrano/mno-enterprise/pull/597
> [MNOE-749] - Fix search on app metrics

- src/app/components/mnoe-staffs-list/mnoe-staffs-list.coffee
- src/app/components/mnoe-staffs-list/mnoe-staffs-list.html
- Listeners registered twice
- Duplicate initial calls
> [MNOE-836] Duplicate request on Staff table

- src/app/index.config.coffee
- src/locales/en-AU.json
Depends on mno-enterprise PR: maestrano/mno-enterprise#612
@alexnoox is there a better way to organise all our interceptors? There are 3 of them.
> [MNOE-110] MnoHub error handling interceptor

- src/app/views/organization/organization.html
- src/locales/en-AU.json
Replace the checkbox with a Yes/No
> [MNOE-860] Update Demo Company UI

- src/app/views/organization/create-user-modal/create-user.controller.coffee
- src/app/views/organization/create-user-modal/create-user.html
- src/locales/en-AU.json
Allow for server error processing. Required for customer customisation.
> [MNOE-887] Better error handling

- src/app/views/user/user.html
> [MNOE-887] Fix locale regression

- src/app/components/mnoe-organizations-local-list/mnoe-organizations-local-list.coffee
- src/app/components/mnoe-organizations-local-list/mnoe-organizations-local-list.html
- src/app/components/mnoe-organizations-local-list/mnoe-organizations-local-list.less
- src/app/components/mnoe-users-local-list/mnoe-users-local-list.coffee
- src/app/components/mnoe-users-local-list/mnoe-users-local-list.html
- src/app/components/mnoe-users-local-list/mnoe-users-local-list.less
- src/app/services/user-roles-helper/user-roles-helper.coffee
- src/app/views/user/user.html
- src/locales/en-AU.json
@ouranos 
@adamaziz15 
I ended up refactoring the frontend API call into a service, so they can be used by both tables.
> [MNOE-921] Add role to user/org table 

- src/app/components/mnoe-orders-list/mnoe-orders-list.html
- src/app/components/mnoe-organizations-local-list/mnoe-organizations-local-list.coffee
- src/app/components/mnoe-organizations-local-list/mnoe-organizations-local-list.html
- src/app/components/mnoe-product-markups-list/mnoe-product-markups-list.html
- src/app/components/mnoe-staffs-list/mnoe-staffs-list.html
- src/app/components/mnoe-staffs-local-list/mnoe-staffs-local-list.html
- src/app/components/mnoe-subscriptions-list/mnoe-subscriptions-list.html
- src/app/components/mnoe-users-local-list/mnoe-users-local-list.html
- src/locales/en-AU.json
This pull request 
1) Fixes loading locales for org info page.
2) Makes a variety of tables resizable.
3) Adds pagination to the user's table/org's table in the orgs info/users info pages.
> [MNOE-906] Improve Tables 

- src/app/components/mnoe-api/admin/tenant.svc.coffee
- src/app/views/settings/general/general.controller.coffee
Should we add a timeout to the polling / interval between two calls?
> [MNOE-970] Poll restart status to know when restart is done

- src/locales/en-AU.json
The panel is called 'Provisioning events'
> [OPALSUP-26] Fix locale

- src/app/components/mnoe-products-list/mnoe-products-list.controller.coffee
- src/app/components/mnoe-subscription-events-list/mnoe-subscription-events-list.coffee
- src/app/components/mnoe-subscription-events-list/mnoe-subscription-events-list.html
- src/app/components/mnoe-subscriptions-list/mnoe-subscriptions-list.coffee
- src/app/services/user-roles-helper/user-roles-helper.coffee
- src/app/views/orders/order.controller.coffee
- src/app/views/products/product.controller.coffee
- src/app/views/products/products.controller.coffee
- src/app/views/settings/apps/apps.controller.coffee
1. Dryed up isAccountManager.
2. Added flag to mnoe-subscription-events-list.
3. Cleaned up mnoe-subscription-events-list with extraneous injections.
> [MNOE-1122] Staff can not approve/reject orders

- src/app/views/settings/apps/apps.controller.coffee
Updated to display all the available products, newly added inclusive, immediately when new products are added and cleared out all the filters.
> [MNOE-1120] Displayed all available products on new products addition

- src/app/views/staff/update-staff-clients-modal/update-staff-clients.html
Fixed faulty pagination issue on search in update staff clients modal
> [MNOE-1141] Fixed faulty pagination display

- src/app/views/settings/apps/apps.controller.coffee
- src/app/views/settings/apps/apps.html
Added loading ellipsis when loading, adding or removing products
> [MNOE-1129] Added loader while loading products

- src/app/views/provisioning/details.controller.coffee
- src/locales/en-AU.json
Porting fixes from maestrano/mno-enterprise-angular#514
Also removed an unused locale?
> [MNOE-1172] Fix bug in subscription action flow

- src/app/views/organization/organization.controller.coffee
> Organization missing dependency

- src/app/views/products/product.controller.coffee
Revert changes to product controller from MNOE-1218
> [MNOE-1229] Pricing Languages

- src/app/views/provisioning/order.controller.coffee
- src/app/views/provisioning/order.html
Added currency selection check in admin panel when placing orders
> [MNOE-1265] Added currency selection check in admin panel

- src/app/components/mnoe-api/admin/organizations.svc.coffee
- src/app/components/mnoe-organizations-list/mnoe-organizations-list.coffee
- src/app/views/staff/update-staff-clients-modal/update-staff-clients.controller.coffee
- src/app/views/sub-tenant/update-clients-modal/update-clients.controller.coffee
Fixed issue with params which were being passed while fetching searched for organizations
- In update clients modal for staff
- In update clients modal for sub tenants
- On home page
> [OPALSUP-299] Fixed issue with organizations' params

- src/app/views/products/product.html
Fixed per_duration `year` value
> [OPAL-544] Not able to approve orders for Local products with recurring plan

- src/app/views/settings/general/general.html
Disable save button on settings page when form is invalid.
> [OPALSUP-343] Settings save button

- src/app/views/home/home.html
- src/locales/en-AU.json
Update organization total count widget label to indicate that the count
is inclusive of demo organizations.
> [MNOE-1295] Metrics widget label

- src/app/components/mno-product-selector/mno-product-selector.controller.coffee
- src/app/components/mno-product-selector/mno-product-selector.html
- src/app/components/mno-product-selector/mno-product-selector.less
- src/app/views/organization/organization.controller.coffee
- src/locales/en-AU.json
- Properly disable the ability to add multiple instances of products
that are not multi_instantiable
> [MNOE-1298][OPALSUP-344] Multi-instantiable products

- src/app/components/mno-product-selector/mno-product-selector.controller.coffee
- src/app/components/mno-product-selector/mno-product-selector.html
- src/app/components/mnoe-config/mnoe-admin-config.svc.coffee
- src/app/components/mnoe-subscriptions-list/mnoe-subscriptions-list.coffee
- src/app/views/organization/organization.controller.coffee
- src/locales/en-AU.json
- Disable ordering if billing details are required
- Disable all app management if billing details or payment are required
- Update mnoe admin config svc with app management requirement settings
> [MNOE-1296] Account mgmt requirements
