maestrano/mnoe-admin-panel

src/app/components/mnoe-config/mnoe-admin-config.svc.coffee, src/app/components/mnoe-users-local-list/mnoe-users-local-list.coffee, src/app/components/mnoe-users-local-list/mnoe-users-local-list.html, src/app/index.default-config.coffee, src/app/index.route.coffee, src/app/views/customers/create-step-1/create-step-1.controller.coffee, src/app/views/customers/create-step-1/create-step-1.html, src/app/views/customers/customers.html, src/app/views/dashboard.controller.coffee, src/app/views/dashboard.layout.html, src/app/views/home/home.controller.coffee, src/app/views/home/home.html, src/app/views/organization/organization.html, src/app/views/user/user.html
@fgourichon @alexnoox add the following feature flags:
```yaml
admin_panel:
impersonation:
disabled: false
staff:
enabled: true
finance:
enabled: true
apps_management:
enabled: true
customer_management:
organization:
enabled: true
user:
enabled: true
```
(See https://github.com/maestrano/mno-enterprise/pull/258)
- impersonation => backported from mnoe
- staff => disable the staff management
- finance => disable the finance page, the financial kpis and the invoices
- apps_management => disabled adding/removing apps (we can still connect them)
- customer_mangement
- organization => Disable customer creation / invite
- user => disable adding users
@alexnoox, a couple questions:
* What do you think of wrapping the `ADMIN_CONFIG` constant in a service? This allow to have proper defaults and a …
=> Feature flags

src/app/views/organization/organization.html
Requires: https://github.com/maestrano/mno-enterprise/pull/260
But it's backward compatible because of the `ng-if`
=> [MNOE-389] Add Customer Invoice download

src/app/components/mnoe-subscriptions-list/mnoe-subscriptions-list.coffee, src/app/components/mnoe-subscriptions-list/mnoe-subscriptions-list.html, src/app/views/orders/orders.html, src/locales/en-AU.json
Break down the order screen to split orders between "orders to action" and "history". Also default the sorting to most recent orders first.
=> [MNOE-664] Breakdown order list screen

src/app/components/intercom/intercom.svc.coffee, src/app/components/mnoe-api/admin/current-user.svc.coffee, src/app/components/mnoe-config/mnoe-admin-config.svc.coffee, src/app/index.controller.coffee, src/app/index.run.coffee, src/index.html
Ability to enabled Intercom in the Admin Panel if it's properly
configured for the dashboard.
We push the admin_role to be able to differentiate admin.
Notes:
* I didn't patch the Intercom loader script as we did for the dashboard as it seems to be working, we'll do more testing in UAT and I'll patch it if needed
* @alexnoox Instead of `IntercomSvc` would it be better to pick a more generic name to be able to abstract the support system we use? (We can alway rename if we have to implement a different system)
=> [MNOE-682] Add Intercom to the Admin Panel

src/app/views/provisioning/order.html
When editing an order, pricing plan selected was not pre-populated
=> [MNOE-764] - Fix pricing plan not being pre-populated

src/app/index.less
@alexnoox This LESS update should take care of an ng-show/ng-hide bug on the admin panel. I will leave comments in the related issue in JIRA. The bug is apparently common and comes from ng-animate, the styling changes prevent the overlap in transitions from ng-show to ng-hide that appear in IE11.
=> Update css for ng-animate bug

src/app/views/customers/create-step-1/create-step-1.less
App titles are not inheriting max-width from icon class
=> [Support] App logo sizes differ in IE11

src/app/components/mnoe-organizations-list/mnoe-organizations-list.coffee, src/app/components/mnoe-organizations-list/mnoe-organizations-list.html, src/app/components/mnoe-users-list/mno-users-list.coffee, src/app/components/mnoe-users-list/mno-users-list.html, src/app/views/customers/customers.html, src/app/views/home/home.html
The components are also used in the Customer tab: should there also be only the 'show all' mode here ?
I made 'show all' by default and left the 'last 10' option but it will be easy to change.
To handle the case where the names are empty when sorting, I use a default (hidden) value of "~" which works well when comparing against alphanumeric characters, is there another (cleaner) way ? 
Changes: 
- Organization & User lists uses mno-ui-element's [sortable-table](https://github.com/maestrano/mno-ui-elements/tree/master/src/components/sortable-table), allowing them to be sorted by columns
- They are sorted by 'created_at' descendant by default
- They do not have a 'Last 10' option anymore
- Their height is responsive, with a maximum cap corresponding to ~11 rows (no scrollbar when below the …
=> [MNOE-777] Improve user and organisations table

src/app/components/mnoe-users-list/mno-users-list.coffee, src/app/views/user/user.html, src/locales/en-AU.json
Needs `user.locked_at` from https://github.com/maestrano/mno-enterprise/pull/580
The lock icon on the user list widget is based on the previous work at #141 [MNOE-777]
=> [MNOE-791] Show user lock status

bower.json, src/app/index.module.coffee, src/app/index.run.coffee, src/index.html
* Uses ng-bind instead of the ng-state-title module
* The title first displays
mnoe_admin_panel.dashboard.layout.title
and then gets translated, there might be a solution for this (ng-cloak didn't work).(@alexnoox an idea?)
This is _only_ on page load (refresh /  type the URL) and not when using the menu
=> [MNOE-793] Fix title on page load

src/app/index.run.coffee, src/app/views/settings/general/general.controller.coffee
This PR should fix the locale issue on the tabs in the settings page. Previously it was being set with `$translate.instant(...)` This caused an issue if you were already on the settings page. When you hit refresh the schema form is attached to the scope before translations were loaded so the locale keys were shown instead of the translations.
=> [MNOE-811] Override tabs template to use angular translate filter

src/app/components/mnoe-config/mnoe-admin-config.svc.coffee, src/app/components/mnoe-organizations-list/mnoe-organizations-list.coffee, src/app/components/mnoe-users-list/mno-users-list.coffee, src/app/views/staff/staff.controller.coffee, src/app/views/staff/staff.html
This add a new "Account Manager" feature flag
- If the feature is enabled, a "staff" user can be assigned to customers and can only see those ones (which is the current behaviour)
- If the feature is disabled, the screen to assign customers is not showing and a staff can see all customers (only difference with "admin" in this case is some screens are limited)
=> [MNOE-823] "Account Manager" feature flag

src/app/components/mnoe-api/admin/users.svc.coffee, src/app/components/mnoe-users-local-list/mnoe-users-local-list.coffee, src/app/components/mnoe-users-local-list/mnoe-users-local-list.html, src/locales/en-AU.json
- For the text-editable email, ability to edit the text by clicking on the fa-icon next to it
- For canceling an invitation or adding a user, simple cross rather than a button before, with a tooltip
- When canceling, by sending the whole object, we can retrieve the user from their id first
=> Invitation management

src/app/components/mnoe-users-local-list/mnoe-users-local-list.coffee, src/app/components/mnoe-users-local-list/mnoe-users-local-list.html, src/app/components/mnoe-users-local-list/mnoe-users-local-list.less, src/app/views/organization/organization.html
* Fix impersonation UI regression when impersonation is disabled
* Fix user table when no organization: only display some columns when in the context of an organization (role, invitation status, impersonation). This was breaking the customer import as the users are displayed without an org.
* Fix edit email link
* Fix UI: same number of columns for all widgets
=> [MNOE-775][MNOE-776] Fix User table

gulp_tasks/misc.js, package.json
It's causing trouble with the deprecation of gulp-utils introduced in
gulp 4.0-alpha3
=> Replace gulp-main-bower-files with main-bower-files

src/app/views/settings/apps/apps.controller.coffee, src/app/views/settings/apps/apps.html
The Settings/Apps screen is Read-Only when the Tenant's
`metadata.app_management` is not set to "tenant"
The metadata is exposed by MNOE via [MNOE#624](https://github.com/maestrano/mno-enterprise/pull/624)
=> [MNOE-821] App Management when Tenant App Management is disabled

src/app/views/staff/create-staff-modal/create-staff.controller.coffee, src/app/views/staff/create-staff-modal/create-staff.html, src/app/views/staff/create-staff-modal/create-staff.less, src/locales/en-AU.json
- If the invited email was already a regular user, a toaster error was displayed
=> We first check that no user has this email. If there is, we update the role, otherwise, same behaviour as before.
=> [EMERAL-122] Add staff when user already exists

src/app/components/mno-product-selector/mno-product-selector.controller.coffee, src/app/components/mno-product-selector/mno-product-selector.html, src/app/views/organization/organization.controller.coffee
When hitting create an order from the organization, we would fetch all the dependencies for all the products.
Now, we only fetch logo and name (what we display), then fetch the details once the product has been selected
=> [MNOE-806] Fetch details of product only when selected for order

src/app/components/mnoe-organizations-local-list/mnoe-organizations-local-list.coffee, src/app/components/mnoe-organizations-local-list/mnoe-organizations-local-list.html, src/app/components/mnoe-users-local-list/mnoe-users-local-list.coffee
Only display the role column when in the context of an user.
This was breaking the customer import as the orgs are displayed without an user.
Same ass #176 but for the other table
=> [MNOE-1031] Fix orgs table when no user

src/app/views/customers/create-step-1/create-step-1.controller.coffee, src/app/views/customers/create-step-1/create-step-1.html
The App selection displayed during customer creation is no longer
compatible with the product workflow.
=> [OPALSUP-75] Hide App selection when provisioning enabled

src/app/components/mnoe-api/admin/users.svc.coffee, src/app/components/mnoe-staffs-list/mnoe-staffs-list.coffee, src/app/views/staff/staff.controller.coffee, src/locales/en-AU.json
* Fix role change confirmation on staff page: Remove the check on the client size as it's no longer in the response and would require an external call.
* Add role change confirmation on staff list
* Improve the confirmation modal text
=> [MNOE-1213] Fix staff role change confirmation

src/app/views/products/product.controller.coffee, src/app/views/provisioning/details.controller.coffee
- Set language for all local product pricings to ensure that they are
all returned when viewing them in the marketplace
- Fix typo in provisioning workflow that prevented some contracts from
going through to their external provider.
=>  [MNOE-1218][MNOE-1219] Product pricings & Fix typo

src/app/views/provisioning/summary.controller.coffee
Add guarding to summary controller to prevent error when product is set
to skip plan selection.
=> [OPAL-513] Locales displayed on "Validate"

src/app/components/mnoe-subscriptions-list/mnoe-subscriptions-list.html
Staged subscriptions are abandoned, which goes through cancel endpoint in mnoe.
=> [MNOE-1260]Add abandon to cancel subscription button

src/locales/en-AU.json
The no_pricing_found and no_pricing_plans_found translations
were slightly inconsistent and have been reworded for clarity.
=> [OPALSUP-302] Update translations for no_pricing_*

src/app/components/mno-product-selector/mno-product-selector.controller.coffee, src/app/components/mno-product-selector/mno-product-selector.html, src/app/components/mnoe-api/admin/products.svc.coffee
The MnoeProduct service is provided product attributes in a dynamic
list of the form [{field:<name>,data:<value>}] by MNOE/Hub. This
information is now flattened into the product objects for use by
the frontend.
Using this, the product selection GUI now uses the tiny description as
as tooltip.
=> [OPALSUP-280] Extract product value attributes in the MnoeProducts service

src/app/components/mnoe-users-local-list/mnoe-users-local-list.coffee, src/app/components/mnoe-users-local-list/mnoe-users-local-list.html, src/app/views/organization/create-user-modal/create-user.controller.coffee
On removing a user from the organisation's list of members, update the
the source list, and then refilter the display list.
Refactored the search code for conciseness, and so it could be called
from the removal code.
Also tweaked the name displayed on successfully adding a user. If the
user already exists, the name will the be the existing record's user
name, not the one the user enters.
=> [OPALSUP-305] Remove user from list-org list

src/app/views/products/product.controller.coffee, src/app/views/products/product.html
Update product view to only allow one pricing plan at a time to be in an edit state.
=> [OPALSUP-258] Reseller price plan not saved

src/app/components/mnoe-config/mnoe-admin-config.svc.coffee, src/app/components/mnoe-staffs-list/mnoe-staffs-list.coffee, src/app/components/mnoe-staffs-list/mnoe-staffs-list.html, src/app/views/staff/staff.controller.coffee, src/app/views/staff/staff.html, src/app/views/staffs/staffs.controller.coffee, src/app/views/staffs/staffs.html
Add a new feature flag (disabled by default) which allow to disable staff edition.
This is useful when the staff list is managed through an external system via API.
Note that the client assignment is still possible (this is controlled by another feature flag)
=> [KAPP-175] Add readOnly staff feature flag
